name: site
dependencies:
  - base

executables:
  site:
    main: main.hs
    dependencies: []

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies: 
      - markdown-unlit
      - hspec
    ghc-options: -pgmL markdown-unlit -optL !pseudo
