name: site
dependencies:
  - base

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies: 
      - markdown-unlit
      - hspec
    ghc-options: -pgmL markdown-unlit -optL !pseudo
